### ISSUE TITLE
Discharge slots take estimated consumption into consideration ?

### ISSUE THREAD

**Issue by Bart39** [stevebuk1/pv_opt#94] opened 2024-01-26 17:56 UTC
When I have a bit more time I will add some logs / screenshots but for context I am only using it in read only mode at the moment and using my own automations.
What I am seeing though for discharge slots is that it will schedule a slot during peak Import/Export costs at 4PM at full power (6000w). Because it doesn't appear to take the consumption into account this means it will drain my battery before the peak finishes at 7PM.
Is this intended ?
Thanks
Mark

**Comment by fboundy** [comment] 2024-01-30 13:51
That's not intended behaviour. Please add some screenshots/log files so I can diagnose

**Comment by fboundy** [comment] 2024-02-11 21:16
Closing this as I believe recent updates should fix this. Please re-open or raise a new issue with logs if it re-occurs

**Closed as completed by fboundy** 2024-02-11 21:16 UTC
